# Ubuntu 20.04
dist: focal
os: linux

# Only build test master & travis
branches:
  only:
  - master
  - travis

# Enable C++ support
language: cpp

addons:
  apt:
    packages: &packages
      - libdrm-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libwayland-dev
      - libx11-xcb-dev
      - libx11-dev
      - libgbm-dev
      - libevdev-dev
      - meson
      - ninja-build
      - libfmt-dev

# Need MYCC and MYCXX as travis overwrites CC and CXX

jobs:
  include:
    - compiler: gcc
      addons:
        apt:
          packages: [*packages, 'g++-7']
      env: MYCC=gcc-7 MYCXX=g++-7

    - compiler: gcc
      addons:
        apt:
          packages: [*packages, 'g++-8']
      env: MYCC=gcc-8 MYCXX=g++-8

    - compiler: gcc
      addons:
        apt:
          packages: [*packages, 'g++-9']
      env: MYCC=gcc-9 MYCXX=g++-9

    - compiler: gcc
      addons:
        apt:
          packages: [*packages, 'g++-10']
      env: MYCC=gcc-10 MYCXX=g++-10

    - compiler: clang
      addons:
        apt:
          packages: [*packages, 'clang-6.0', 'llvm-6.0-dev']
      env: MYCC=clang-6.0 MYCXX=clang++-6.0

    - compiler: clang
      addons:
        apt:
          packages: [*packages, 'clang-7', 'llvm-7-dev']
      env: MYCC=clang-7 MYCXX=clang++-7

    - compiler: clang
      addons:
        apt:
          packages: [*packages, 'clang-8', 'llvm-8-dev']
      env: MYCC=clang-8 MYCXX=clang++-8

    - compiler: clang
      addons:
        apt:
          packages: [*packages, 'clang-9', 'llvm-9-dev']
      env: MYCC=clang-9 MYCXX=clang++-9

    - compiler: clang
      addons:
        apt:
          packages: [*packages, 'clang-10', 'llvm-10-dev']
      env: MYCC=clang-10 MYCXX=clang++-10

# Build steps
script:
  - CC=$MYCC CXX=$MYCXX meson -Dkmscube=true -Dpykms=enabled -Dwerror=true -Db_lto=true build
  - ninja -v -C build

notifications:
  email:
    - tomi.valkeinen@iki.fi
